language: c
sudo: required
matrix:
  include:
    - compiler: gcc
      script:
        - make test
        - make valgrind-quiet
    - compiler: clang
      script:
        - make test
        - make valgrind-quiet
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - python-pip
      env:
        - BUILD_TYPE=Coverage
      script:
        - make test
        - |
          sudo pip install gcovr;
          make coverage;
          find build/coverage -name "*.gc*" -type f -delete;
          bash <(curl -s https://codecov.io/bash) -X search -f build/coverage.xml;
    - compiler: gcc
      env:
        global:
        - secure: "ZbJEZzYTPA2T8wJ0er2PBpCWHHnPmTLY26d+n9ESnm6/76UYg1rAOuArZS+FDWk2juJzJ8E58b84ZbX0DcbhapWoizvD73z6l9ZQ9lkIt9sN/Dl2aq7suQwk4aw+IL5jmTCSnxpw6WJgjrt43947zjG6fh7gXhSYzAqyNHbsWIIZncmbHELbkuRZkn+BgzneEGMWLufmeFgQHED3lNEcTe4Ge3T48I25t7Lc4avlpgwTV/pugAgGi+vgpouX2lcDlgV3Ub1gV8K7cSwneQ94561LNe3SYlFxbh4yDdRBD0vVNRbNB2jzumrmML7BmqQdflzbKgcxzt3zhd//BRXr3hPytnHMPVqnXIHl2YlO0KXQS2D1J5BBSV7MqKwkxtZbmMjYLR3/8yfQU802zroF8W4xyZc4WtWqC/wVeDq008BgHHz8vWHET4IfYDkyMp6GfWEkkLykkKpY0fTcl9bkJBLrG83fzGhfOw7aBkz6xhIgTJqVHO5JGI1ZgiilqZ3oQihTSz+uOTk/WD6SsfHeBRfrrJYea9WaqURGa1rBSAg4gk+ftguB5uj8VwO8hRNRTZQjkJUq9/OJo1KdUUc4h1QfgnInVM/bumUu7F+8zotBU63PBs7yVtY4jz6Hh+9UpX2v8K/i2ypKgRwQYNTZbPUb69RFovxRv/gvRXUUAxc="
      addons:
        coverity_scan:
          project:
            name: "tlsa/libcyaml"
            description: "C library for reading and writing YAML."
          notification_email: tlsa@netsurf-browser.org
          build_command_prepend: "make clean"
          build_command: "make"
          branch_pattern: coverity_scan
      script:
        - make

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y valgrind libyaml-dev
